from typing import Any, Optional, Union

class Matrix:
    def __init__(self, a: float, b: float) -> None: ...

class Document:
    def __init__(self, filename: str) -> None: ...
    def load_page(self, page_num: int) -> Page: ...
    def close(self) -> None: ...
    @property
    def page_count(self) -> int: ...

class Page:
    def get_pixmap(self, matrix: Optional[Matrix] = None, dpi: Optional[float] = None) -> Pixmap: ...
    def get_text(self, mode: str = "text") -> str: ...

class Pixmap:
    def save(self, filename: str) -> None: ...

def open(filename: str) -> Document: ...
